
language: cpp
compiler: gcc
dist: bionic

before_install:
  - sudo add-apt-repository -y ppa:berndporr/dsp
  - sudo apt-get update
  - git clone https://github.com/berndporr/iir1.git
  - cd iir1
  - mkdir -p build && cd build
  - cmake ..
  - make && sudo make install
  - cd ../..

install:
 - sudo apt-get install qtdeclarative5-dev-tools
 - sudo apt-get install libqwt-qt5-dev
 
script: 
- cd Rpi_end
- cd 'unit tests in RPI end'
- cd 'Data filter+udp sending unit'
- qmake
- make 



